version: "2.1"

services:
  dev:
    image: beecast
    build: .
    environment:
      PORT: 3333
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/beecast
      - node_modules:/beecast/node_modules
    ports:
      - 3333:3333

volumes:
  node_modules: {}
